const currencies = [
    { code: 'ALL', symbol: 'Lek', name: 'Albania Lek' },
    { code: 'AFN', symbol: '؋', name: 'Afghanistan Afghani' },
    { code: 'ARS', symbol: '$', name: 'Argentina Peso' },
    { code: 'AWG', symbol: 'ƒ', name: 'Aruba Guilder' },
    { code: 'AUD', symbol: '$', name: 'Australia Dollar' },
    { code: 'AZN', symbol: '₼', name: 'Azerbaijan Manat' },
    { code: 'BSD', symbol: '$', name: 'Bahamas Dollar' },
    { code: 'BBD', symbol: '$', name: 'Barbados Dollar' },
    { code: 'BYN', symbol: 'Br', name: 'Belarus Ruble' },
    { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar' },
    { code: 'BMD', symbol: '$', name: 'Bermuda Dollar' },
    { code: 'BOB', symbol: '$b', name: 'Bolivia Bolíviano' },
    { code: 'BAM', symbol: 'KM', name: 'Bosnia and Herzegovina Convertible Mark' },
    { code: 'BWP', symbol: 'P', name: 'Botswana Pula' },
    { code: 'BGN', symbol: 'лв', name: 'Bulgaria Lev' },
    { code: 'BRL', symbol: 'R$', name: 'Brazil Real' },
    { code: 'BND', symbol: '$', name: 'Brunei Darussalam Dollar' },
    { code: 'KHR', symbol: '៛', name: 'Cambodia Riel' },
    { code: 'CAD', symbol: '$', name: 'Canada Dollar' },
    { code: 'KYD', symbol: '$', name: 'Cayman Islands Dollar' },
    { code: 'CLP', symbol: '$', name: 'Chile Peso' },
    { code: 'CNY', symbol: '¥', name: 'China Yuan Renminbi' },
    { code: 'COP', symbol: '$', name: 'Colombia Peso' },
    { code: 'CRC', symbol: '₡', name: 'Costa Rica Colon' },
    { code: 'HRK', symbol: 'kn', name: 'Croatia Kuna' },
    { code: 'CUP', symbol: '₱', name: 'Cuba Peso' },
    { code: 'CZK', symbol: 'Kč', name: 'Czech Republic Koruna' },
    { code: 'DKK', symbol: 'kr', name: 'Denmark Krone' },
    { code: 'DOP', symbol: 'RD$', name: 'Dominican Republic Peso' },
    { code: 'XCD', symbol: '$', name: 'East Caribbean Dollar' },
    { code: 'EGP', symbol: '£', name: 'Egypt Pound' },
    { code: 'SVC', symbol: '$', name: 'El Salvador Colon' },
    { code: 'EUR', symbol: '€', name: 'Euro Member Countries' },
    { code: 'FKP', symbol: '£', name: 'Falkland Islands Pound' },
    { code: 'FJD', symbol: '$', name: 'Fiji Dollar' },
    { code: 'GHS', symbol: '¢', name: 'Ghana Cedi' },
    { code: 'GIP', symbol: '£', name: 'Gibraltar Pound' },
    { code: 'GTQ', symbol: 'Q', name: 'Guatemala Quetzal' },
    { code: 'GGP', symbol: '£', name: 'Guernsey Pound' },
    { code: 'GYD', symbol: '$', name: 'Guyana Dollar' },
    { code: 'HNL', symbol: 'L', name: 'Honduras Lempira' },
    { code: 'HKD', symbol: '$', name: 'Hong Kong Dollar' },
    { code: 'HUF', symbol: 'Ft', name: 'Hungary Forint' },
    { code: 'ISK', symbol: 'kr', name: 'Iceland Krona' },
    { code: 'INR', symbol: '₹', name: 'India Rupee' },
    { code: 'IDR', symbol: 'Rp', name: 'Indonesia Rupiah' },
    { code: 'IRR', symbol: '﷼', name: 'Iran Rial' },
    { code: 'IMP', symbol: '£', name: 'Isle of Man Pound' },
    { code: 'ILS', symbol: '₪', name: 'Israel Shekel' },
    { code: 'JMD', symbol: 'J$', name: 'Jamaica Dollar' },
    { code: 'JPY', symbol: '¥', name: 'Japan Yen' },
    { code: 'JEP', symbol: '£', name: 'Jersey Pound' },
    { code: 'KZT', symbol: 'лв', name: 'Kazakhstan Tenge' },
    { code: 'KPW', symbol: '₩', name: 'Korea North Won' },
    { code: 'KRW', symbol: '₩', name: 'Korea South Won' },
    { code: 'KGS', symbol: 'лв', name: 'Kyrgyzstan Som' },
    { code: 'LAK', symbol: '₭', name: 'Laos Kip' },
    { code: 'LBP', symbol: '£', name: 'Lebanon Pound' },
    { code: 'LRD', symbol: '$', name: 'Liberia Dollar' },
    { code: 'MKD', symbol: 'ден', name: 'Macedonia Denar' },
    { code: 'MYR', symbol: 'RM', name: 'Malaysia Ringgit' },
    { code: 'MUR', symbol: '₨', name: 'Mauritius Rupee' },
    { code: 'MXN', symbol: '$', name: 'Mexico Peso' },
    { code: 'MNT', symbol: '₮', name: 'Mongolia Tughrik' },
    { code: 'MZN', symbol: 'MT', name: 'Mozambique Metical' },
    { code: 'NAD', symbol: '$', name: 'Namibia Dollar' },
    { code: 'NPR', symbol: '₨', name: 'Nepal Rupee' },
    { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antilles Guilder' },
    { code: 'NZD', symbol: '$', name: 'New Zealand Dollar' },
    { code: 'NIO', symbol: 'C$', name: 'Nicaragua Cordoba' },
    { code: 'NGN', symbol: '₦', name: 'Nigeria Naira' },
    { code: 'NOK', symbol: 'kr', name: 'Norway Krone' },
    { code: 'OMR', symbol: '﷼', name: 'Oman Rial' },
    { code: 'PKR', symbol: '₨', name: 'Pakistan Rupee' },
    { code: 'PAB', symbol: 'B/.', name: 'Panama Balboa' },
    { code: 'PYG', symbol: 'Gs', name: 'Paraguay Guarani' },
    { code: 'PEN', symbol: 'S/.', name: 'Peru Sol' },
    { code: 'PHP', symbol: '₱', name: 'Philippines Peso' },
    { code: 'PLN', symbol: 'zł', name: 'Poland Zloty' },
    { code: 'QAR', symbol: '﷼', name: 'Qatar Riyal' },
    { code: 'RON', symbol: 'lei', name: 'Romania Leu' },
    { code: 'RUB', symbol: '₽', name: 'Russia Ruble' },
    { code: 'SHP', symbol: '£', name: 'Saint Helena Pound' },
    { code: 'SAR', symbol: '﷼', name: 'Saudi Arabia Riyal' },
    { code: 'RSD', symbol: 'Дин.', name: 'Serbia Dinar' },
    { code: 'SCR', symbol: '₨', name: 'Seychelles Rupee' },
    { code: 'SGD', symbol: '$', name: 'Singapore Dollar' },
    { code: 'SBD', symbol: '$', name: 'Solomon Islands Dollar' },
    { code: 'SOS', symbol: 'S', name: 'Somalia Shilling' },
    { code: 'ZAR', symbol: 'R', name: 'South Africa Rand' },
    { code: 'LKR', symbol: '₨', name: 'Sri Lanka Rupee' },
    { code: 'SEK', symbol: 'kr', name: 'Sweden Krona' },
    { code: 'CHF', symbol: 'CHF', name: 'Switzerland Franc' },
    { code: 'SRD', symbol: '$', name: 'Suriname Dollar' },
    { code: 'SYP', symbol: '£', name: 'Syria Pound' },
    { code: 'TWD', symbol: 'NT$', name: 'Taiwan New Dollar' },
    { code: 'THB', symbol: '฿', name: 'Thailand Baht' },
    { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
    { code: 'TRY', symbol: '₺', name: 'Turkey Lira' },
    { code: 'TVD', symbol: '$', name: 'Tuvalu Dollar' },
    { code: 'UAH', symbol: '₴', name: 'Ukraine Hryvnia' },
    { code: 'GBP', symbol: '£', name: 'United Kingdom Pound' },
    { code: 'USD', symbol: '$', name: 'United States Dollar' },
    { code: 'UYU', symbol: '$U', name: 'Uruguay Peso' },
    { code: 'UZS', symbol: 'лв', name: 'Uzbekistan Som' },
    { code: 'VEF', symbol: 'Bs', name: 'Venezuela Bolívar' },
    { code: 'VND', symbol: '₫', name: 'Viet Nam Dong' },
    { code: 'YER', symbol: '﷼', name: 'Yemen Rial' },
    { code: 'ZWD', symbol: 'Z$', name: 'Zimbabwe Dollar' }
];