const stores = [
    { name: 'Amazon', url: 'https://amazon.com/s?k:' },
    { name: 'Newegg', url: 'https://newegg.com/p/pl?d:' },
    { name: 'AliExpress', url: 'https://aliexpress.com/wholesale?SearchText:' },
    { name: 'eBay', url: 'https://ebay.com/sch/i.html?_nkw:' },
    { name: 'Microcenter', url: 'https://microcenter.com/search/search_results.aspx?Ntt:' },
    { name: 'B&H Photo', url: 'https://bhphotovideo.com/c/search?Ntt:' },
    { name: 'Best Buy', url: 'https://bestbuy.com/site/searchpage.jsp?st:' },
    { name: 'Walmart', url: 'https://walmart.com/search?q:' },
    { name: 'Target', url: 'https://target.com/s?searchTerm:' },
    { name: 'Costco', url: 'https://costco.com/CatalogSearch?keyword:' },
    { name: 'Adorama', url: 'https://adorama.com/search?searchinfo:' },
    { name: 'Memory Express', url: 'https://memoryexpress.com/Search/Index?Search:' },
    { name: 'Canada Computers', url: 'https://canadacomputers.com/search?keywords:' },
    { name: 'Overclockers UK', url: 'https://overclockers.co.uk/search?search:' },
    { name: 'Scan UK', url: 'https://scan.co.uk/search?q:' },
    { name: 'Ebuyer UK', url: 'https://ebuyer.com/search?q:' },
    { name: 'Box UK', url: 'https://box.co.uk/search?q:' },
    { name: 'Mindfactory', url: 'https://mindfactory.de/search_result.php?search_query:' },
    { name: 'Caseking', url: 'https://caseking.de/search?search:' },
    { name: 'Alternate DE', url: 'https://alternate.de/search?query:' },
    { name: 'LDLC', url: 'https://ldlc.com/recherche/?search:' },
    { name: 'Materiel.net', url: 'https://materiel.net/recherche/' },
    { name: 'Coolblue', url:'https://coolblue.nl/search?query:' },
    { name: 'Digitec', url:'https://digitec.ch/en/search?q:' },
    { name: 'Alza', url:'https://alza.cz/search?query:' },
    { name: 'Scorptec', url:'https://scorptec.com.au/search?q:' },
    { name: 'Mwave AU', url:'https://mwave.com.au/search?q:' },
    { name: 'Centre Com', url:'https://centrecom.com.au/search?q:' },
    { name: 'PCCG', url:'https://pccasegear.com/search?q:' },
    { name: 'PB Tech NZ', url:'https://pbtech.co.nz/search?q:' },
    { name: 'Kabum', url:'https://kabum.com.br/busca?query:' },
    { name: 'Pichau', url:'https://pichau.com.br/search?q:' },
    { name: 'Terabyteshop', url:'https://terabyteshop.com.br/busca?termo:' },
    { name: 'Cyberpower', url:'https://cyberpowerpc.com/search?keyword:' },
    { name: 'iBuyPower', url:'https://ibuypower.com/shop/search?q:' },
    { name: 'Origin PC', url:'https://originpc.com/search?q:' },
    { name: 'Maingear', url:'https://maingear.com/search?q:' },
    { name: 'NZXT', url:'https://nzxt.com/search?q:' },
    { name: 'Digital Storm', url:'https://digitalstorm.com/search?query:' },
    { name: 'Corsair', url:'https://corsair.com/search?q:' },
    { name: 'Razer', url:'https://razer.com/search?q:' },
    { name: 'Dell', url:'https://dell.com/search?q:' },
    { name: 'HP', url:'https://hp.com/search?q:' },
    { name: 'Lenovo', url:'https://lenovo.com/search?q:' },
    { name: 'ASUS', url:'https://asus.com/search?q:' },
    { name: 'MSI', url:'https://msi.com/search?q:' },
    { name: 'Acer', url:'https://acer.com/search?q:' },
    { name: 'Gigabyte', url:'https://gigabyte.com/search?q:' },
    { name: 'Zotac', url:'https://zotac.com/search?q:' },
    { name: 'Thermaltake', url:'https://thermaltake.com/search?q:' },
    { name: 'Cooler Master', url:'https://coolermaster.com/search?q:' },
    { name: 'Fractal Design', url:'https://fractal-design.com/search?q:' },
    { name: 'be quiet!', url:'https://bequiet.com/en/search?q:' },
    { name: 'Noctua', url:'https://noctua.at/en/search?q:' },
    { name: 'Crucial', url:'https://crucial.com/search?q:' },
    { name: 'Kingston', url:'https://kingston.com/search?q:' },
    { name: 'Western Digital', url:'https://westerndigital.com/search?q:' },
    { name: 'Seagate', url:'https://seagate.com/search?q:' },
    { name: 'Samsung', url:'https://samsung.com/search?q:' },
    { name: 'Intel', url:'https://intel.com/content/www/us/en/search.html?q:' },
    { name: 'AMD', url:'https://amd.com/search?q:' },
    { name: 'NVIDIA', url:'https://nvidia.com/search?q:' },
    { name: 'EVGA', url:'https://evga.com/search/?q:' },
    { name: 'PNY', url:'https://pny.com/search?q:' },
    { name: 'Monoprice', url:'https://monoprice.com/search?q:' },
    { name: 'Performance PCs', url:'https://performance-pcs.com/search?q:' },
    { name: 'Titan Rig', url:'https://titanrig.com/search?q:' },
    { name: 'EKWB', url:'https://ekwb.com/search?q:' },
    { name: 'Watercooling UK', url:'https://watercoolinguk.co.uk/search?q:' },
    { name: 'Aquatuning', url:'https://aquatuning.co.uk/search?q:' },
    { name: 'ModMyMods', url:'https://modmymods.com/search?q:' },
    { name: 'FrozenCPU', url:'https://frozencpu.com/search?q:' },
    { name: 'HighFlow', url:'https://highflow.nl/search?q:' },
    { name: 'PCDiga', url:'https://pcdiga.com/search?q:' },
    { name: 'Computer Lounge NZ', url:'https://computerlounge.co.nz/search?q:' },
    { name: 'Playtech NZ', url:'https://playtech.co.nz/search?q:' },
    { name: 'Notebooksbilliger', url:'https://notebooksbilliger.de/search?q:' },
    { name: 'Cyberport', url:'https://cyberport.de/search?q:' },
    { name: 'ARLT', url:'https://arlt.com/search?q:' },
    { name: 'KMComputer', url:'https://kmcomputer.de/search?q:' },
    { name: 'Conrad', url:'https://conrad.de/search?q:' },
    { name: 'Reichelt', url:'https://reichelt.com/search?q:' },
    { name: 'Voelkner', url:'https://voelkner.de/search?q:' },
    { name: 'Pollin', url:'https://pollin.de/search?q:' },
    { name: 'Digitalo', url:'https://digitalo.de/search?q:' },
    { name: 'Proshop', url:'https://proshop.de/search?q:' },
    { name: 'Galaxus DE', url:'https://galaxus.de/search?q:' },
    { name: 'Galaxus CH', url:'https://galaxus.ch/search?q:' },
    { name: 'Steg Electronics', url:'https://steg-electronics.ch/search?q:' },
    { name: 'Brack', url:'https://brack.ch/search?q:' },
    { name: 'Prodimex', url:'https://prodimex.ch/search?q:' },
    { name: 'PC Restretto', url:'https://pcrestretto.ch/search?q:' },
    { name: 'Meinto', url:'https://meinto.de/search?q:' },
    { name: 'Elkjop', url:'https://elkjop.no/search?q:' },
    { name: 'Power', url:'https://power.no/search?q:' },
    { name: 'Dustin', url:'https://dustinhome.se/search?q:' },
    { name: 'Multicom', url:'https://multicom.no/search?q:' },
    { name: 'NetonNet', url:'https://netonnet.se/search?q:' },
    { name: 'Jimms', url:'https://jimms.fi/search?q:' },
    { name: 'Datatronic', url:'https://datatronic.dk/search?q:' },
    { name: 'Computer City', url:'https://computercity.com/search?q:' },
    { name: 'Komplett', url:'https://komplett.se/search?q:' },
    { name: 'Megakko', url:'https://megekko.nl/search?q:' },
    { name: 'Azerty', url:'https://azerty.nl/search?q:' },
    { name: 'Alternate NL', url:'https://alternate.nl/search?q:' },
    { name: 'Alternate BE', url:'https://alternate.be/search?q:' },
    { name: 'Informatique', url:'https://informatique.nl/search?q:' },
    { name: 'Tones', url:'https://tones.be/search?q:' },
    { name: 'Codgeb', url:'https://codgeb.com/search?q:' },
    { name: 'Grosbill', url:'https://grosbill.com/search?q:' },
    { name: 'TopAchat', url:'https://topachat.com/search?q:' },
    { name: 'Infomax Paris', url:'https://infomaxparis.com/search?q:' },
    { name: 'Hardware.fr', url:'https://hardware.fr/search?q:' },
    { name: 'Rue du Commerce', url:'https://rueducommerce.fr/search?q:' },
    { name: 'Cdiscount', url:'https://cdiscount.com/search?q:' },
    { name: 'Fnac', url:'https://fnac.com/search?q:' },
    { name: 'Darty', url:'https://darty.com/search?q:' },
    { name: 'Eprice', url:'https://eprice.it/search?q:' },
    { name: 'Drako', url:'https://drako.it/search?q:' },
    { name: 'Yeppon', url:'https://yeppon.it/search?q:' },
    { name: 'BPM Power', url:'https://bpm-power.com/search?q:' },
    { name: 'AKInformatic', url:'https://akinformatic.com/search?q:' },
    { name: 'Nexths', url:'https://nexths.it/search?q:' },
    { name: 'Monclick', url:'https://monclick.it/search?q:' },
    { name: 'Alternate IT', url:'https://alternate.it/search?q:' },
    { name: 'Coolmod', url:'https://coolmod.com/search?q:' },
    { name: 'Xtremmedia', url:'https://xtremmedia.com/search?q:' },
    { name: 'Neobyte', url:'https://neobyte.es/search?q:' },
    { name: 'VS Gaming', url:'https://vsgaming.es/search?q:' },
    { name: 'Izarmicro', url:'https://izarmicro.net/search?q:' },
    { name: 'Globaldata', url:'https://globaldata.pt/search?q:' },
    { name: 'Chiptec', url:'https://chiptec.net/search?q:' },
    { name: 'Aquapc', url:'https://aquapc.com/search?q:' },
    { name: 'Alza SK', url:'https://alza.sk/search?q:' },
    { name: 'Alza HU', url:'https://alza.hu/search?q:' },
    { name: 'Alza AT', url:'https://alza.at/search?q:' },
    { name: 'Alza UK', url:'https://alza.co.uk/search?q:' },
    { name: 'eMAG', url:'https://emag.ro/search?q:' },
    { name: 'PC Garage', url:'https://pcgarage.ro/search?q:' },
    { name: 'Cel', url:'https://cel.ro/search?q:' },
    { name: 'Evomag', url:'https://evomag.ro/search?q:' },
    { name: 'Sigmanet', url:'https://sigmanet.lv/search?q:' },
    { name: '1A LV', url:'https://1a.lv/search?q:' },
    { name: 'Dateks', url:'https://dateks.lv/search?q:' },
    { name: 'RD Veikals', url:'https://rdveikals.lv/search?q:' },
    { name: 'Skybuy', url:'https://skybuy.lt/search?q:' },
    { name: 'Kilobaitas', url:'https://kilobaitas.lt/search?q:' },
    { name: 'Varle', url:'https://varle.lt/search?q:' },
    { name: '1A LT', url:'https://1a.lt/search?q:' },
    { name: 'OX', url:'https://ox.ee/search?q:' },
    { name: 'Faun', url:'https://faun.ee/search?q:' },
    { name: 'Arvutitark', url:'https://arvutitark.ee/search?q:' },
    { name: '1A EE', url:'https://1a.ee/search?q:' },
    { name: 'Morele', url:'https://morele.net/search?q:' },
    { name: 'X-Kom', url:'https://x-kom.pl/search?q:' },
    { name: 'Proline PL', url:'https://proline.pl/search?q:' },
    { name: 'Komputronik', url:'https://komputronik.pl/search?q:' },
    { name: 'Scanshop', url:'https://scanshop.pl/search?q:' },
    { name: 'HardPC', url:'https://hardpc.pl/search?q:' },
    { name: 'Nettop', url:'https://nettop.pl/search?q:' },
    { name: 'Gral', url:'https://gral.pl/search?q:' },
    { name: 'Novatech', url:'https://novatech.co.uk/search?q:' },
    { name: 'CCL Online', url:'https://cclonline.com/search?q:' },
    { name: 'Aria PC', url:'https://aria.co.uk/search?q:' },
    { name: 'Elara IE', url:'https://elara.ie/search?q:' },
    { name: 'DirectDial', url:'https://directdial.com/search?q:' },
    { name: 'PC-Canada', url:'https://pc-canada.com/search?q:' },
    { name: 'ShopRBC', url:'https://shoprbc.com/search?q:' },
    { name: 'Carbon Computing', url:'https://carboncomputing.com/search?q:' },
    { name: 'Mikes Computer Shop', url:'https://mikescomputershop.com/search?q:' },
    { name: 'Vuugo', url:'https://vuugo.com/search?q:' },
    { name: 'AsiaTech', url:'https://asiatech.ca/search?q:' },
    { name: 'Central Computer', url:'https://centralcomputer.com/search?q:' },
    { name: 'Frys', url:'https://frys.com/search?q:' },
    { name: 'Outlet PC', url:'https://outletpc.com/search?q:' },
    { name: 'SuperBiiz', url:'https://superbiiz.com/search?q:' },
    { name: 'PC Nation', url:'https://pcnation.com/search?q:' },
    { name: 'Provantage', url:'https://provantage.com/search?q:' },
    { name: 'OWC', url:'https://macsales.com/search?q:' },
    { name: 'TigerDirect', url:'https://tigerdirect.com/search?q:' },
    { name: 'CompUSA', url:'https://compusa.com/search?q:' },
    { name: 'CDW', url:'https://cdw.com/search?q:' },
    { name: 'Zones', url:'https://zones.com/search?q:' },
    { name: 'Insight', url:'https://insight.com/search?q:' },
    { name: 'PC Connection', url:'https://pcconnection.com/search?q:' },
    { name: 'SHI', url:'https://shi.com/search?q:' },
    { name: 'PCM', url:'https://pcm.com/search?q:' },
    { name: 'Markertek', url:'https://markertek.com/search?q:' },
    { name: 'Sweetwater', url:'https://sweetwater.com/search?q:' },
    { name: 'zZounds', url:'https://zzounds.com/search?q:' },
    { name: 'Sam Ash', url:'https://samash.com/search?q:' },
    { name: 'American Musical', url:'https://americanmusical.com/search?q:' },
    { name: 'Guitar Center', url:'https://guitarcenter.com/search?q:' },
    { name: 'Musicians Friend', url:'https://musiciansfriend.com/search?q:' },
    { name: 'Audio Advisor', url:'https://audioadvisor.com/search?q:' },
    { name: 'Crutchfield', url:'https://crutchfield.com/search?q:' },
    { name: 'Parts Express', url:'https://parts-express.com/search?q:' },
    { name: 'PrimeABGB', url:'https://primeabgb.com/search?q:' },
    { name: 'MD Computers', url:'https://mdcomputers.in/search?q:' },
    { name: 'Vedant Computers', url:'https://vedantcomputers.com/search?q:' },
    { name: 'IT Depot', url:'https://theitdepot.com/search?q:' },
    { name: 'PC Studio', url:'https://pcstudio.in/search?q:' },
    { name: 'EliteHubs', url:'https://elitehubs.com/search?q:' },
    { name: 'The Mall', url:'https://themall.in/search?q:' },
    { name: 'Croma', url:'https://croma.com/search?q:' },
    { name: 'Reliance Digital', url:'https://reliancedigital.in/search?q:' },
    { name: 'Computech', url:'https://computechstore.in/search?q:' },
    { name: 'ModX Computers', url:'https://modxcomputers.com/search?q:' },
    { name: 'Oasis IT Store', url:'https://oasisitstore.in/search?q:' },
    { name: 'Vishal Peripherals', url:'https://vishalperipherals.com/search?q:' },
    { name: 'SMC International', url:'https://smcinternational.in/search?q:' },
    { name: 'IT Gadgetsonline', url:'https://itgadgetsonline.com/search?q:' },
    { name: 'Nakoda IT Solutions', url:'https://nakodaitsol.com/search?q:' },
    { name: 'Volted PC', url:'https://voltedpc.in/search?q:' },
    { name: 'PLE Computers', url:'https://ple.com.au/search?q:' },
    { name: 'Shopping Express', url:'https://shoppingexpress.com.au/search?q:' },
    { name: 'Computer Alliance', url:'https://computeralliance.com.au/search?q:' },
    { name: 'Umart', url:'https://umart.com.au/search?q:' },
    { name: 'MSY', url:'https://msy.com.au/search?q:' },
    { name: 'JW Computers', url:'https://jw.com.au/search?q:' },
    { name: 'CPL Online', url:'https://cplonline.com.au/search?q:' },
    { name: 'Gamedude', url:'https://gamedude.com.au/search?q:' },
    { name: 'I-Tech', url:'https://i-tech.com.au/search?q:' },
    { name: 'Eyoyo', url:'https://eyoyo.com.au/search?q:' },
    { name: 'Wireless1', url:'https://wireless1.com.au/search?q:' },
    { name: 'Superwarehouse', url:'https://superwarehouse.com.au/search?q:' },
    { name: 'Mighty Ape NZ', url:'https://mightyape.co.nz/search?q:' },
    { name: 'Ascent', url:'https://ascent.co.nz/search?q:' },
    { name: 'Extreme PC', url:'https://extremepc.co.nz/search?q:' },
    { name: 'Just Laptops', url:'https://justlaptops.co.nz/search?q:' },
    { name: 'Dragon PC', url:'https://dragonpc.co.nz/search?q:' },
    { name: 'Invade PC', url:'https://invadepc.co.za/search?q:' },
    { name: 'Wootware', url:'https://wootware.co.za/search?q:' },
    { name: 'Evetech', url:'https://evetech.co.za/search?q:' },
    { name: 'Rebel Tech', url:'https://rebeltech.co.za/search?q:' },
    { name: 'Titan Ice', url:'https://titan-ice.co.za/search?q:' },
    { name: 'Proline ZA', url:'https://proline.co.za/search?q:' },
    { name: 'Dreamware Tech', url:'https://dreamwaretech.co.za/search?q:' },
    { name: 'ComX Computers', url:'https://comx-computers.co.za/search?q:' },
    { name: 'PC Link', url:'https://pc-link.co.za/search?q:' },
    { name: 'Frontosa', url:'https://frontosa.co.za/search?q:' },
    { name: 'Matrix Warehouse', url:'https://matrixwarehouse.co.za/search?q:' },
    { name: 'Computers Only', url:'https://computersonly.co.za/search?q:' },
    { name: 'Custom Computers', url:'https://customcomputers.co.za/search?q:' },
    { name: 'Takealot', url:'https://takealot.com/search?q:' },
    { name: 'Loot', url:'https://loot.co.za/search?q:' },
    { name: 'Bidorbuy', url:'https://bidorbuy.co.za/search?q:' },
    { name: 'Hachi Tech', url:'https://hachi.tech/search?q:' },
    { name: 'Dynacore', url:'https://dynacore.com.sg/search?q:' },
    { name: 'Bizgram', url:'https://bizgram.com/search?q:' },
    { name: 'Fuwell', url:'https://fuwell.com.sg/search?q:' },
    { name: 'Trade Pac', url:'https://tradepac.com.sg/search?q:' },
    { name: 'Cybermind', url:'https://cybermind.com.sg/search?q:' },
    { name: 'PC Themes', url:'https://pc-themes.com/search?q:' },
    { name: 'Gamepro SG', url:'https://gameprosg.com/search?q:' },
    { name: 'Sim Lim', url:'https://simlim.sg/search?q:' },
    { name: 'Hardwarezone', url:'https://hardwarezone.com.sg/search?q:' },
    { name: 'Lazada SG', url:'https://lazada.sg/search?q:' },
    { name: 'Shopee SG', url:'https://shopee.sg/search?q:' },
    { name: 'Qoo10 SG', url:'https://qoo10.sg/search?q:' },
    { name: 'iPrice SG', url:'https://iprice.sg/search?q:' },
    { name: 'Amazon SG', url:'https://amazon.sg/search?q:' },
    { name: 'Lazada MY', url:'https://lazada.com.my/search?q:' },
    { name: 'Shopee MY', url:'https://shopee.com.my/search?q:' },
    { name: 'Lelong', url:'https://lelong.com.my/search?q:' },
    { name: 'Viewnet', url:'https://viewnet.com.my/search?q:' },
    { name: 'Jayacom', url:'https://jayacom.com.my/search?q:' },
    { name: 'All IT', url:'https://allitonline.com.my/search?q:' },
    { name: 'Ideal Tech', url:'https://idealtech.com.my/search?q:' },
    { name: 'Brightstar Comp', url:'https://brightstarcomp.com.my/search?q:' },
    { name: 'Montech', url:'https://montech.com.my/search?q:' },
    { name: 'PC Byte', url:'https://pcbyte.com.my/search?q:' },
    { name: 'Lazada TH', url:'https://lazada.co.th/search?q:' },
    { name: 'Shopee TH', url:'https://shopee.co.th/search?q:' },
    { name: 'JIB', url:'https://jib.co.th/search?q:' },
    { name: 'Advice', url:'https://advice.co.th/search?q:' },
    { name: 'Invade IT', url:'https://invadeit.co.th/search?q:' },
    { name: 'Compute & More', url:'https://computeandmore.com/search?q:' },
    { name: 'IHaveCPU', url:'https://ihavecpu.com/search?q:' },
    { name: 'Jedi Cool', url:'https://jedicool.com/search?q:' },
    { name: 'Busitek', url:'https://busitek.com/search?q:' },
    { name: 'Lazada PH', url:'https://lazada.com.ph/search?q:' },
    { name: 'Shopee PH', url:'https://shopee.ph/search?q:' },
    { name: 'PCX', url:'https://pcx.com.ph/search?q:' },
    { name: 'Easy PC', url:'https://easypc.com.ph/search?q:' },
    { name: 'Dynaquest', url:'https://dynaquestpc.com/search?q:' },
    { name: 'PCHub', url:'https://pchubonline.com/search?q:' },
    { name: 'Gilmore Computer', url:'https://gilmorecomputer.com/search?q:' },
    { name: 'Villman', url:'https://villman.com/search?q:' },
    { name: 'Complink', url:'https://complink.com.ph/search?q:' },
    { name: 'Benson', url:'https://benson.com.ph/search?q:' },
    { name: 'Tokopedia', url:'https://tokopedia.com/search?q:' },
    { name: 'Bukalapak', url:'https://bukalapak.com/search?q:' },
    { name: 'Blibli', url:'https://blibli.com/search?q:' },
    { name: 'Shopee ID', url:'https://shopee.co.id/search?q:' },
    { name: 'Lazada ID', url:'https://lazada.co.id/search?q:' },
    { name: 'Bhinneka', url:'https://bhinneka.com/search?q:' },
    { name: 'Enter Komputer', url:'https://enterkomputer.com/search?q:' },
    { name: 'Rakitan', url:'https://rakitan.com/search?q:' },
    { name: 'Tonix Computer', url:'https://tonixcomputer.co.id/search?q:' },
    { name: 'Quantum Komputer', url:'https://quantumkomputer.com/search?q:' },
    { name: 'Yodobashi', url:'https://yodobashi.com/search?q:' },
    { name: 'Bic Camera', url:'https://biccamera.com/search?q:' },
    { name: 'Sofmap', url:'https://sofmap.com/search?q:' },
    { name: 'Tsukumo', url:'https://tsukumo.co.jp/search?q:' },
    { name: 'Dospara', url:'https://dospara.co.jp/search?q:' },
    { name: 'PC-Koubou', url:'https://pc-koubou.jp/search?q:' },
    { name: 'Ark PC', url:'https://ark-pc.co.jp/search?q:' },
    { name: 'Amazon JP', url:'https://amazon.co.jp/s?k:' },
    { name: 'Rakuten', url:'https://rakuten.co.jp/search?q:' },
    { name: 'Yahoo JP', url:'https://shopping.yahoo.co.jp/search?q:' },
    { name: 'Danawa', url:'https://danawa.com/search?q:' },
    { name: 'Compuzone', url:'https://compuzone.co.kr/search?q:' },
    { name: 'Icoda', url:'https://icoda.co.kr/search?q:' },
    { name: 'Joyzen', url:'https://joyzen.co.kr/search?q:' },
    { name: 'Gmarket KR', url:'https://gmarket.co.kr/search?q:' },
    { name: 'Auction KR', url:'https://auction.co.kr/search?q:' },
    { name: '11st', url:'https://11st.co.kr/search?q:' },
    { name: 'Coupang', url:'https://coupang.com/search?q:' },
    { name: 'Interpark', url:'https://interpark.com/search?q:' },
    { name: 'Naver', url:'https://search.shopping.naver.com/search/all?query:' },
    { name: 'CoolPC', url:'https://coolpc.com.tw/search?q:' },
    { name: 'Autobuy', url:'https://autobuy.tw/search?q:' },
    { name: 'PChome', url:'https://pchome.com.tw/search?q:' },
    { name: 'Momo', url:'https://momoshop.com.tw/search?q:' },
    { name: 'Ruten', url:'https://ruten.com.tw/search?q:' },
    { name: 'Shopee TW', url:'https://shopee.tw/search?q:' },
    { name: 'Yahoo TW', url:'https://tw.search.yahoo.com/search?p:' },
    { name: 'iSunfar', url:'https://isunfar.com.tw/search?q:' },
    { name: 'TK3C', url:'https://tk3c.com.tw/search?q:' },
    { name: 'Sinya', url:'https://sinya.com.tw/search?q:' },
    { name: 'Trexplus', url:'https://trexplus.com/search?q:' },
    { name: 'Clarion Computers', url:'https://clarioncomputers.in/search?q:' },
    { name: 'National PC', url:'https://nationalpc.in/search?q:' },
    { name: 'TPS Technologies', url:'https://tpstechnologies.in/search?q:' },
    { name: 'Tech97', url:'https://tech97.in/search?q:' },
    { name: 'Hardware Mana', url:'https://hardwaremana.com/search?q:' },
    { name: 'PCBazaar', url:'https://pcbazaar.in/search?q:' },
    { name: 'TLG Gaming', url:'https://tlggaming.com/search?q:' },
    { name: 'TreXplus', url:'https://trexplus.com/search?q:' },
    { name: 'Clarion Computers', url:'https://clarioncomputers.in/search?q:' },
    { name: 'National PC', url:'https://nationalpc.in/search?q:' },
    { name: 'TPS Technologies', url:'https://tpstechnologies.in/search?q:' },
    { name: 'Tech97', url:'https://tech97.in/search?q:' },
    { name: 'Hardware Mana', url:'https://hardwaremana.com/search?q:' },
    { name: 'PCBazaar', url:'https://pcbazaar.in/search?q:' },
    { name: 'TLG Gaming', url:'https://tlggaming.com/search?q:' },
    { name: 'Smart Link', url:'https://smartlink.in/search?q:' },
    { name: 'Krishna Computers', url:'https://krishnacomputers.in/search?q:' },
    { name: 'Manoj Computers', url:'https://manojcomputers.in/search?q:' },
    { name: 'PCLink', url:'https://pclink.in/search?q:' },
    { name: 'Computer Warehouse', url:'https://computerwarehouse.in/search?q:' },
];